### PR TITLE
ishglodevops bugfix#00 Update

### PR DESCRIPTION
**Pull request by ishglodevops**
Please review my code prior to merging

### CODE REVIEW

**Comment by samueto1** [comment]
change approved

**Comment by elvis-ngeh** [comment]
approved

**Comment by lameade26** [comment]
Approved

**Review by chamberlain96 — APPROVED** [review]

**Comment by chamberlain96** [comment]
approved

**Review by lameade26 — APPROVED** [review]

**Review by deanoffaculty — COMMENTED** [review]
Thats ok

**Pull request merged**
